# Generated by Django 3.2 on 2021-04-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_photo_post_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='mainPhoto',
        ),
    ]
